### ISSUE TITLE
Rename config-map to be more consistent with controller name

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/ixia-c-operator#20]
Check if it's feasible to rename the file to ixiatg-config.yaml and assess compatibility issues.

**Comment by ashutshkumr** [comment]
Summary of upcoming changes:
- Rename `ixia-configmap.yaml` to `ixiatg-configmap.yaml`
- Use GHCR image paths for ixia-c images as the default one in ixiatg-configmap.yaml instead of GCP (since vendors do not have access to GCP container registry)
- Include `ixia-c-hw-server` as a new image (applicable only for ixia-c-hw deployment)

**Comment by ashutshkumr** [comment]
@open-traffic-generator/google FYI, since this impacts deployment workflow.

**Comment by jasdeep-hundal** [comment]
LGTM from the HW perspective

**Comment by ashutshkumr** [comment]
Fixed in https://github.com/open-traffic-generator/ixia-c-operator/releases/tag/v0.3.1
